version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: shimmybot_db
    environment:
      POSTGRES_DB: shimmybot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ../ShimmybotVolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      